### ISSUE TITLE
Crash upon pet pickup using Keybind

### ISSUE THREAD

**Issue by Bumbullbee** [shiftthedev/PickablePets#16]
Hello, I seem to be having an issue where I crash the internal server if picking up a pet when using the keybind setting. This is odd, because when I use the Sneak+Right click setting I'm able to pick them up just fine. Whenever I crash using the keybind setting and then load back into the world, I still find the pet in my inventory. I'm able to place them back down either way, so no issues there. They even show back up as the correct model/health/etc when placing "crashed pickup" pet. I've used multiple keybinds and all result in the crash.

In case I'm using the wrong verbiage, the "Crash internal server" refers to me being in a single player world, but getting booted out to the multiplayer select menu after getting the error screen.

Here's my crash log, fair warning, I've got a ton of mods installed. This is very likely to be an incompatibility of some sort, but I'm not seeing any references to other mods. I've updated dependencies to latest versions as well. Before I updated dependencies, it would crash the game entirely, not just an internal server crash.

[latest.log](https://github.com/shiftthedev/PickablePets/files/15210528/latest.log)

The error in question is here:
<details>
  <summary>Async Entity Unload Error</summary>
  
  [12:47:04] [Netty Server IO #1/ERROR]: Encountered exception while handling in channel with name "pickablepets:input"
java.util.ConcurrentModificationException: Async entity unload
	at net.minecraft.class_3898.handler$bjk000$c2me-fixes-general-threading-issues$preventAsyncEntityUnload(class_3898.java:7435) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_18716(class_3898.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_18753(class_3215.java:480) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218$class_5526.method_31437(class_3218.java:1581) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218$class_5526.method_31797(class_3218.java:1536) ~[client-intermediary.jar:?]
	at net.minecraft.class_5579.method_31850(class_5579.java:220) ~[client-intermediary.jar:?]
	at net.minecraft.class_5579$class_5580.method_31750(class_5579.java:115) ~[client-intermediary.jar:?]
	at dev.architectury.hooks.level.entity.fabric.EntityHooksImpl$1.method_31750(EntityHooksImpl.java:48) ~[architectury-9.2.14-fabric.jar:?]
	at net.minecraft.class_1297.method_31745(class_1297.java:3636) ~[client-intermediary.jar:?]
	at net.minecraft.class_1297.method_5650(class_1297.java:402) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_5650(class_1309.java:712) ~[client-intermediary.jar:?]
	at com.shiftthedev.pickablepets.utils.Helper.Pickup(Helper.java:68) ~[PickablePets-1.2.3+1.20.1-fabric.jar:?]
	at com.shiftthedev.pickablepets.network.PickupPacket$Server.lambda$receive$1(PickupPacket.java:39) ~[PickablePets-1.2.3+1.20.1-fabric.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at com.shiftthedev.pickablepets.network.PickupPacket$Server.receive(PickupPacket.java:38) ~[PickablePets-1.2.3+1.20.1-fabric.jar:?]
	at dev.architectury.networking.fabric.NetworkManagerImpl.lambda$registerC2SReceiver$0(NetworkManagerImpl.java:80) ~[architectury-9.2.14-fabric.jar:?]
	at dev.architectury.networking.transformers.PacketTransformer$1.inbound(PacketTransformer.java:47) ~[architectury-9.2.14-fabric.jar:?]
	at dev.architectury.networking.fabric.NetworkManagerImpl.lambda$registerC2SReceiver$1(NetworkManagerImpl.java:75) ~[architectury-9.2.14-fabric.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:85) ~[fabric-networking-api-v1-1.3.11+1802ada577-4657550f9c265bf4.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:39) ~[fabric-networking-api-v1-1.3.11+1802ada577-4657550f9c265bf4.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101) ~[fabric-networking-api-v1-1.3.11+1802ada577-4657550f9c265bf4.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.handle(ServerPlayNetworkAddon.java:80) ~[fabric-networking-api-v1-1.3.11+1802ada577-4657550f9c265bf4.jar:?]
	at net.minecraft.class_3244.handler$dhi000$fabric-networking-api-v1$handleCustomPayloadReceivedAsync(class_3244.java:2500) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12075(class_3244.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_2817.method_12199(class_2817.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_2817.method_11054(class_2817.java:7) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:160) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:52) ~[client-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:47:04] [Server thread/INFO]: Bumbullbee lost connection: Internal Exception: java.util.ConcurrentModificationException: Async entity unload
  
</details>

**Comment by shiftthedev** [comment]
thanks for reporting. I'll add this to my to-do list and look into it.

**Comment by arctlw** [comment]
Bump, same thing happens to me. It's just the internal server crashes and I get booted to the server selection page.

**Comment by Bumbullbee** [comment]
I gave it a go with the new update and a crashed again with the same error type and all. Thought I'd let you know since I was the one to open this a while back

**Comment by shiftthedev** [comment]
most likely is a mod conflict. because i've changed how the keybind works in the latest version.

**Comment by arctlw** [comment]
As an update, the keybind is working fine for me in the latest version for 1.20.1.
Thanks for the fix!
