### ISSUE TITLE
[1.20.1] Invalid player data

### ISSUE THREAD

**Issue by Star-Jirachi** [shiftthedev/PickablePets#19]
I add Domestication Innovation (it adds tameable rabbits) and Pickable Pets in my server.
I pick up a rabbit, then I left the game.
When I want to join the game again, It says "Invalid player data".
It's the report:
~~~
[Server thread/ERROR] [net.minecraft.server.network.ServerLoginPacketListenerImpl]: Couldn't place player in world
net.minecraft.ReportedException: Loading entity NBT
	at net.minecraft.world.entity.Entity.m_20258_(Entity.java:2089) ~[server-1.20.1-20230612.114412-srg.jar%23520!/:?]
	at net.minecraft.world.level.storage.PlayerDataStorage.m_78435_(PlayerDataStorage.java:89) ~[server-1.20.1-20230612.114412-srg.jar%23520!/:?]
	at net.minecraft.server.players.PlayerList.m_11224_(PlayerList.java:426) ~[server-1.20.1-20230612.114412-srg.jar%23520!/:?]
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:184) ~[server-1.20.1-20230612.114412-srg.jar%23520!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:178) ~[server-1.20.1-20230612.114412-srg.jar%23520!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:165) ~[server-1.20.1-20230612.114412-srg.jar%23520!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:77) ~[server-1.20.1-20230612.114412-srg.jar%23520!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:272) ~[server-1.20.1-20230612.114412-srg.jar%23520!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:149) ~[server-1.20.1-20230612.114412-srg.jar%23520!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1172) ~[server-1.20.1-20230612.114412-srg.jar%23520!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:349) ~[server-1.20.1-20230612.114412-srg.jar%23520!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1074) ~[server-1.20.1-20230612.114412-srg.jar%23520!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:904) ~[server-1.20.1-20230612.114412-srg.jar%23520!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23520!/:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.LivingEntity.m_5446_()" because the return value of "net.minecraft.world.entity.OwnableEntity.m_269323_()" is null
	at com.shiftthedev.pickablepets.utils.PetInfo.<init>(PetInfo.java:56) ~[PickablePets-1.2.3+1.20.1-forge.jar%23487!/:?]
	at com.shiftthedev.pickablepets.utils.CachedPets.addOldPet(CachedPets.java:107) ~[PickablePets-1.2.3+1.20.1-forge.jar%23487!/:?]
	at net.minecraft.world.item.ItemStack.handler$zoh000$ofImpl(ItemStack.java:1191) ~[server-1.20.1-20230612.114412-srg.jar%23520!/:?]
	at net.minecraft.world.item.ItemStack.m_41712_(ItemStack.java) ~[server-1.20.1-20230612.114412-srg.jar%23520!/:?]
	at net.minecraft.world.entity.player.Inventory.m_36035_(Inventory.java:505) ~[server-1.20.1-20230612.114412-srg.jar%23520!/:?]
	at net.minecraft.world.entity.player.Player.m_7378_(Player.java:804) ~[server-1.20.1-20230612.114412-srg.jar%23520!/:?]
	at net.minecraft.server.level.ServerPlayer.m_7378_(ServerPlayer.java:363) ~[server-1.20.1-20230612.114412-srg.jar%23520!/:?]
	at net.minecraft.world.entity.Entity.m_20258_(Entity.java:2032) ~[server-1.20.1-20230612.114412-srg.jar%23520!/:?]
	... 14 more
[Server thread/INFO] [net.minecraft.server.network.ServerLoginPacketListenerImpl]: com.mojang.authlib.GameProfile@25be9110[id=bc6ea5a1-2f95-3dbf-9eeb-02ff051d4b02,name=Star_Jirachi,properties={},legacy=false] (/118.114.58.99:58888) lost connection: Invalid player data
[Server thread/WARN] [net.minecraft.network.Connection]: handleDisconnection() called twice

**Comment by Star-Jirachi** [comment]
I cannot sure what cause this problem.

**Comment by shiftthedev** [comment]
I'll look into it as soon as I can

**Comment by Star-Jirachi** [comment]
> I'll look into it as soon as I can

OK, thanks :)
