### ISSUE TITLE
Pickable Pets(1.2.0) makes my Minecraft(1.20.1) Fabric(0.15.3) server fail to start

### ISSUE THREAD

**Issue by htd-02** [shiftthedev/PickablePets#8]
Hey !
My server fails to start with Pickable Pets 1.2.0 for Minecraft 1.20.1. It runs fine if I remove Pickable Pets and keep all other mods.

Error log :
```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'pickablepets'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.3.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric.jar:0.11.2]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_746
	at com.shiftthedev.pickablepets.PPRegistry.lambda$static$1(PPRegistry.java:28) ~[PickablePets-1.2.0+1.20.1-fabric.jar:?]
	at dev.architectury.registry.registries.fabric.RegistrarManagerImpl$RegistrarImpl.register(RegistrarManagerImpl.java:210) ~[architectury-9.1.12-fabric.jar:?]
	at dev.architectury.registry.registries.DeferredRegister.register(DeferredRegister.java:76) ~[architectury-9.1.12-fabric.jar:?]
	at com.shiftthedev.pickablepets.PPRegistry.register(PPRegistry.java:44) ~[PickablePets-1.2.0+1.20.1-fabric.jar:?]
	at com.shiftthedev.pickablepets.PickablePets.init(PickablePets.java:31) ~[PickablePets-1.2.0+1.20.1-fabric.jar:?]
	at com.shiftthedev.pickablepets.fabric.PickablePetsFabric.onInitialize(PickablePetsFabric.java:10) ~[PickablePets-1.2.0+1.20.1-fabric.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.3.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at com.shiftthedev.pickablepets.PPRegistry.lambda$static$1(PPRegistry.java:28) ~[PickablePets-1.2.0+1.20.1-fabric.jar:?]
	at dev.architectury.registry.registries.fabric.RegistrarManagerImpl$RegistrarImpl.register(RegistrarManagerImpl.java:210) ~[architectury-9.1.12-fabric.jar:?]
	at dev.architectury.registry.registries.DeferredRegister.register(DeferredRegister.java:76) ~[architectury-9.1.12-fabric.jar:?]
	at com.shiftthedev.pickablepets.PPRegistry.register(PPRegistry.java:44) ~[PickablePets-1.2.0+1.20.1-fabric.jar:?]
	at com.shiftthedev.pickablepets.PickablePets.init(PickablePets.java:31) ~[PickablePets-1.2.0+1.20.1-fabric.jar:?]
	at com.shiftthedev.pickablepets.fabric.PickablePetsFabric.onInitialize(PickablePetsFabric.java:10) ~[PickablePets-1.2.0+1.20.1-fabric.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.3.jar:?]
	... 7 more
```

- Minecraft Version 1.20.1
- Fabric version 0.15.3
- Mods :
    - Architectury API 9.1.12+fabric
    - Concurrent Chunk Management Engine 0.2.0+alpha.11.0+1.20.1
    - Cloth Config API 11.1.118+fabric
    - Fabric API 0.91.0+1.20.1
    - FerriteCore 6.0.1
    - Lithium mc1.20.1-0.11.2
    - MemoryLeakFix v1.1.2
    - Better Nether Map 3.0.0-1.20.1
    - Pickable Pets 1.2.0+1.20.1
    - RideablePolarBears 1.0.0-1.20.1-fabric
    - Starlight 1.1.2+1.20

I'm barely getting back into managing a Minecraft server so it could also very well be me missing something, sorry if that's the case !

**Comment by shiftthedev** [comment]
I'll look into it

**Comment by Wolris** [comment]
Happened to my forge server as well.  Great mod, love to see it work on the server!

**Comment by shiftthedev** [comment]
i've found the problem and should have a fix out next week

**Comment by shiftthedev** [comment]
try version [1.2.1](https://legacy.curseforge.com/minecraft/mc-mods/pickable-pets) and if possible let me know if this is still happening

**Comment by htd-02** [comment]
Server starts without any error, same for client and the mod features work from what I've seen so far.
Thanks a lot for the quick fix !
